### ISSUE TITLE
Break builds for l10n exports with single quotes: use apostrophe instead

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/android-automation-tools#4]
These are in the photon guidelines - https://design.firefox.com/photon/copy/punctuation.html - and I recently came across this in practice: https://github.com/mozilla-l10n/firefoxtv-l10n/pull/7

We may want to check with Delphine to figure out what other export checks could be automated.

**Comment by pocmo** [comment]
We do have some placeholder checks in Focus here:
https://github.com/mozilla-mobile/focus-android/blob/master/tools/l10n/check_translations.py
